version: 2.1
orbs:
  node: circleci/node@4.3.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: yarn test
          command: yarn test:coverage --ci --color --reporters=default --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT: ./tmp/test-results/jest.xml
      - store_test_results:
          path: ./tmp/test-results

  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint

  audit:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn audit

workflows:
  version: 2
  commit:
    jobs:
      - test
      - lint
      - audit:
          filters:
            branches:
              only:
                - main
  cron:
    jobs:
      - test
      - lint
      - audit
    triggers:
      - schedule:
          cron: "0 13 * * *"
          filters:
            branches:
              only:
                - main
