name: Automerge

on:
  workflow_dispatch

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.10.0 # https://github.com/marketplace/actions/merge-pull-requests
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_DELETE_BRANCH: true
          MERGE_LABELS: "!Do Not Merge,!work in progress"
          MERGE_METHOD: "squash"
