name: Require Pull Request Labels

permissions:
  pull-requests: read  # Read PR reviews and labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  check_reviews:
    runs-on: ubuntu-latest
    outputs:
      reviews: ${{ steps.set-get_reviews.outputs.data }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_reviews
        with:
          route: GET ${{ github.event.pull_request.url }}/reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  require_pr_labels:
    runs-on: ubuntu-latest
    needs: [check_reviews]
    steps:
      - name: Debug reviews response
        env:
          REVIEWS_RESPONSE: ${{ needs.check_reviews.outputs.reviews }}
        run: echo "$REVIEWS_RESPONSE"
      - uses: mheap/github-action-required-labels@v1
        if: contains(steps.get_reviews.*.state, 'APPROVED')
        with:
          mode: exactly
          count: 0
          labels: "pending-acceptance"
      - uses: mheap/github-action-required-labels@v1
        if: contains(steps.get_reviews.*.state, 'APPROVED')
        with:
          mode: minimum
          count: 1
          labels: "accepted, chore, dependencies"
