name: Require Pull Request Labels

on:
  pull_request:
    types: [labeled, unlabeled]
  pull_request_review:
    types: [submitted, edited]
  push:

jobs:
  require_pr_labels:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "pending-acceptance"
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "accepted, chore, dependencies"
