name: Require Pull Request Labels

permissions:
  pull-requests: none  # Labels are maybe present in metadata already

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize]

jobs:
  require_pr_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "pending-acceptance"
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "accepted, chore, dependencies"
